"""Add Seat and Ticket models

Revision ID: a29058ed2aa9
Revises: 452964ce55b6
Create Date: 2026-06-21 18:58:16.041034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a29058ed2aa9'
down_revision: Union[str, Sequence[str], None] = '452964ce55b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opponent', sa.String(), nullable=True),
    sa.Column('is_home', sa.Boolean(), nullable=True),
    sa.Column('date_match', sa.Date(), nullable=True),
    sa.Column('bayern_goals', sa.Integer(), nullable=True),
    sa.Column('opponent_goals', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('row', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    op.create_index(op.f('ix_seats_match_id'), 'seats', ['match_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('seat_id', sa.Integer(), nullable=True),
    sa.Column('purchase_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seat_id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_match_id'), 'tickets', ['match_id'], unique=False)
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['user_id'], unique=False)
    op.drop_index(op.f('ix_match_id'), table_name='match')
    op.drop_table('match')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('opponent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_home', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('bayern_goals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('opponent_goals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_match', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('match_pkey'))
    )
    op.create_index(op.f('ix_match_id'), 'match', ['id'], unique=False)
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_match_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_seats_match_id'), table_name='seats')
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
