"""Initial schema: Players and Matches

Revision ID: b25c59bf22d0
Revises: 452fa18437ca
Create Date: 2026-06-13 14:28:43.789738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25c59bf22d0'
down_revision: Union[str, Sequence[str], None] = '452fa18437ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opponent', sa.String(), nullable=True),
    sa.Column('is_home', sa.Boolean(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('bayern_goals', sa.Integer(), nullable=True),
    sa.Column('opponent_goals', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_id'), 'match', ['id'], unique=False)
    op.drop_index(op.f('ix_maches_id'), table_name='maches')
    op.drop_table('maches')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('opponent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_home', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('bayern_goals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('opponent_goals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('maches_pkey'))
    )
    op.create_index(op.f('ix_maches_id'), 'maches', ['id'], unique=False)
    op.drop_index(op.f('ix_match_id'), table_name='match')
    op.drop_table('match')
    # ### end Alembic commands ###
