"""Initial schema: Players and Matches

Revision ID: e2d0faea00ce
Revises: b25c59bf22d0
Create Date: 2026-06-13 14:37:35.254306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d0faea00ce'
down_revision: Union[str, Sequence[str], None] = 'b25c59bf22d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('date_match', sa.Date(), nullable=True))
    op.drop_column('match', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('match', 'date_match')
    # ### end Alembic commands ###
